# coding: utf-8

# 映画
movie = Category.create(name: "映画")
movie_1 = movie.children.create(name: "SF/ファンタジー")
movie_2 = movie.children.create(name: "ロボット/メカ")
movie_3 = movie.children.create(name: "アクション/バトル")
movie_4 = movie.children.create(name: "コメディ/ギャグ")
movie_5 = movie.children.create(name: "ロマンス/恋愛/ラブコメ")
movie_6 = movie.children.create(name: "ファミリー/ホーム")
movie_7 = movie.children.create(name: "ホラー/スプリッター")
movie_8 = movie.children.create(name: "ドラマ/青春")
movie_9 = movie.children.create(name: "アドベンチャー/冒険")
movie_10 = movie.children.create(name: "音楽/ミュージカル")
movie_11 = movie.children.create(name: "スポーツ")
movie_12 = movie.children.create(name: "ミステリー/サスペンス/推理")
movie_13 = movie.children.create(name: "ドキュメンタリー")
movie_14 = movie.children.create(name: "ヤクザ/任侠")
movie_15 = movie.children.create(name: "医療")
movie_16 = movie.children.create(name: "刑事")
movie_17 = movie.children.create(name: "政治")
movie_18 = movie.children.create(name: "ヒューマン")
movie_19 = movie.children.create(name: "アニメーション")
movie_20 = movie.children.create(name: "スペクタクル")
movie_21 = movie.children.create(name: "ノンフィクション")

# ドラマ
drama = Category.create(name: "ドラマ")
drama_1 = drama.children.create(name: "SF/ファンタジー")
drama_2 = drama.children.create(name: "ロボット/メカ")
drama_3 = drama.children.create(name: "アクション/バトル")
drama_4 = drama.children.create(name: "コメディ/ギャグ")
drama_5 = drama.children.create(name: "ロマンス/恋愛/ラブコメ")
drama_6 = drama.children.create(name: "ファミリー/ホーム")
drama_7 = drama.children.create(name: "ホラー/スプリッター")
drama_8 = drama.children.create(name: "学園/青春")
drama_9 = drama.children.create(name: "アドベンチャー/冒険")
drama_10 = drama.children.create(name: "音楽/ミュージカル")
drama_11 = drama.children.create(name: "スポーツ")
drama_12 = drama.children.create(name: "ミステリー/サスペンス/推理")
drama_13 = drama.children.create(name: "ドキュメンタリー")
drama_14 = drama.children.create(name: "ヤクザ/任侠")
drama_15 = drama.children.create(name: "医療")
drama_16 = drama.children.create(name: "刑事")
drama_17 = drama.children.create(name: "政治")
drama_18 = drama.children.create(name: "ヒューマン")
drama_19 = drama.children.create(name: "時代劇/歴史/伝記")
drama_20 = drama.children.create(name: "ノンフィクション")

# アニメ
anime = Category.create(name: "アニメ")
anime_1 = anime.children.create(name: "SF/ファンタジー")
anime_2 = anime.children.create(name: "ロボット/メカ")
anime_3 = anime.children.create(name: "アクション/バトル")
anime_4 = anime.children.create(name: "コメディ/ギャグ")
anime_5 = anime.children.create(name: "ロマンス/恋愛/ラブコメ")
anime_6 = anime.children.create(name: "ファミリー/ホーム")
anime_7 = anime.children.create(name: "ホラー/スプリッター")
anime_8 = anime.children.create(name: "学園/青春")
anime_9 = anime.children.create(name: "アドベンチャー/冒険")
anime_10 = anime.children.create(name: "音楽/ミュージカル")
anime_11 = anime.children.create(name: "スポーツ")
anime_12 = anime.children.create(name: "ミステリー/サスペンス/推理")
anime_13 = anime.children.create(name: "ヤクザ/任侠")
anime_14 = anime.children.create(name: "医療")
anime_15 = anime.children.create(name: "刑事")
anime_16 = anime.children.create(name: "政治")
anime_17 = anime.children.create(name: "ヒューマン")
anime_18 = anime.children.create(name: "日常/ほのぼの")
anime_19 = anime.children.create(name: "歴史/伝記")

# ゲーム
game = Category.create(name: "ゲーム")
game_1 = game.children.create(name: "シューティング")
game_1.children.create([{name: "固定シューティング(例：スペースインベーダー)"},{name: "スクロールシューティング(例：グラディウス)"},{name: "アクションシューティング(例：メタルスラッグ)"},{name: "ガンシューティング(例：タイムクライシス)"},{name: "ファーストパーソンシューティング(FPS)(例：COLL OF DUTY)"},{name: "サードパーソンシューティング(TPS)(例：バイオハザード・スプラトゥーン)"}])
game_2 = game.children.create(name: "アクション")
game_2.children.create([{name: "ドットイート(例：パックマン)"},{name: "プラットフォーマー(例：スーパーマリオブラザーズ)"},{name: "ベルトスクロールアクション(例：ファイナルファイト)"},{name: "対戦アクション(例：大乱闘スマッシュブラザーズ)"},{name: "ハンティングアクション(例：モンスターハンター)"},{name: "ステルス(例：アサシンクリード)"},{name: "クライムアクション(例：グランドセフトオート)"},{name: "対戦格闘ゲーム(例：ストリートファイター)"}])
game_3 = game.children.create(name: "アドベンチャー(例：ボートピア連続殺人事件)")
game_4 = game.children.create(name: "ロールプレイング")
game_4.children.create([{name: "ローグライク(例：不思議のダンジョン)"},{name: "アクションRPG(例：ゼルダの伝説・ダークソウル)"},{name: "シミュレーションRPG(例：ファイアーエンブレム)"},{name: "ハックアンドスラッシュ(例：ドラゴンクエスト)"}])
game_5 = game.children.create(name: "パズル(例：テトリス・ぷよぷよ)")
game_6 = game.children.create(name: "レース(例：マリオカート)")
game_7 = game.children.create(name: "シミュレーション")
game_7.children.create([{name: "ウォーシミュレーション(例：三國志・クラッシュオブクラン)"},{name: "経営シミュレーション(例：シムシティ)"},{name: "育成シミュレーション(例：ウイニングポスト)"},{name: "箱庭ゲーム(例：牧場物語・どうぶつの森)"}])
game_8 = game.children.create(name: "スポーツ(例：パワプロ)")
game_9 = game.children.create(name: "ボード(例：桃太郎電鉄・マリオパーティー)")
game_10 = game.children.create(name: "音楽(例：リズム天国)")
game_11 = game.children.create(name: "オープンワールド(例：龍が如く)")
game_12 = game.children.create(name: "サンドボックス(例：Minecraft)")